apiVersion: apps/v1
kind: Deployment
metadata:
  name: tafarn-frontend
  namespace: toot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tafarn
      part: frontend
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: tafarn
        part: frontend
    spec:
      volumes:
        - name: conf
          configMap:
            name: tafarn-conf
        - name: keys
          secret:
            secretName: tafarn-keys
        - name: media
          persistentVolumeClaim:
            claimName: tafarn-media
      containers:
        - name: frontend
          image: theenbyperor/tafarn:5da4af4b4bdc76640e1ea7752e8f8336333cae3f
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: INFO
            - name: ROCKET_ENV
              value: production
            - name: ROCKET_PORT
              value: "80"
            - name: ROCKET_ADDRESS
              value: "::"
          envFrom:
            - prefix: "ROCKET_"
              configMapRef:
                name: tafarn-conf
            - prefix: "ROCKET_"
              secretRef:
                name: tafarn-oidc
            - prefix: "ROCKET_"
              secretRef:
                name: tafarn-celery
            - prefix: "ROCKET_"
              secretRef:
                name: tafarn-secrets
          volumeMounts:
            - mountPath: "/media"
              name: media
            - mountPath: "/keys"
              name: keys
            - mountPath: "/tafarn/Rocket.toml"
              name: conf
              subPath: "Rocket.toml"
          ports:
            - containerPort: 80