apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tafarn-frontend
  namespace: toot
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: tafarn
              part: nginx
      ports:
        - port: 80
          protocol: TCP
  podSelector:
    matchLabels:
      app: tafarn
      part: frontend
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tafarn-nginx
  namespace: toot
spec:
  podSelector:
    matchLabels:
      app: tafarn
      part: nginx
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80