kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tafarn-media
  namespace: toot
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi